CREATE TABLE IF NOT EXISTS query_history (
  player_id INTEGER REFERENCES player(id),
  game_id INTEGER REFERENCES game(id),
  team_id INTEGER REFERENCES team(id),
  season_year INTEGER REFERENCES season(year),
  home_team_id INTEGER REFERENCES team(id),
  away_team_id INTEGER REFERENCES team(id),
  event_type VARCHAR(50) NOT NULL,
  shot_made BOOLEAN NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  shot_type VARCHAR(50) NOT NULL,
  basic_zone VARCHAR(50) NOT NULL,
  zone_name VARCHAR(100) NOT NULL,
  zone_abb VARCHAR(20) NOT NULL,
  zone_range VARCHAR(50) NOT NULL,
  loc_x FLOAT NOT NULL,
  loc_y FLOAT NOT NULL,
  shot_distance INTEGER NOT NULL,
  qtr SMALLINT NOT NULL,
  total_time_left_secs SMALLINT NOT NULL,
  mins_left SMALLINT NOT NULL,
  secs_left SMALLINT NOT NULL,
  position VARCHAR(20) NOT NULL,
  position_group VARCHAR(20) NOT NULL,
  game_date TIMESTAMP WITH TIME ZONE NOT NULL,
  returned_shots INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);