-- CREATE TABLE IF NOT EXISTS query_history (
--   player_id INTEGER[] DEFAULT ARRAY[]::INTEGER[],
--   team_id INTEGER[] DEFAULT ARRAY[]::INTEGER[],
--   game_id INTEGER[] DEFAULT ARRAY[]::INTEGER[],
--   season_year INTEGER[] DEFAULT ARRAY[]::INTEGER[],
--   quarter INTEGER[] DEFAULT ARRAY[]::INTEGER[],
--   start_game_date TIMESTAMP WITH TIME ZONE,
--   end_game_date TIMESTAMP WITH TIME ZONE,
--   game_location VARCHAR(20),
--   start_time_left INTEGER,
--   returned_shots INTEGER DEFAULT 0,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );

ALTER TABLE query_history
DROP CONSTRAINT IF EXISTS query_history_player_id_fkey,
DROP CONSTRAINT IF EXISTS query_history_game_id_fkey,
DROP CONSTRAINT IF EXISTS query_history_team_id_fkey,
DROP CONSTRAINT IF EXISTS query_history_season_year_fkey;

ALTER TABLE query_history
ALTER COLUMN player_id
  TYPE INTEGER[] USING CASE WHEN player_id IS NULL THEN ARRAY[]::INTEGER[] ELSE ARRAY[player_id] END,
ALTER COLUMN player_id
  SET DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE query_history
ALTER COLUMN game_id
  TYPE INTEGER[] USING CASE WHEN game_id IS NULL THEN ARRAY[]::INTEGER[] ELSE ARRAY[game_id] END,
ALTER COLUMN game_id
  SET DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE query_history
ALTER COLUMN team_id
  TYPE INTEGER[] USING CASE WHEN team_id IS NULL THEN ARRAY[]::INTEGER[] ELSE ARRAY[team_id] END,
ALTER COLUMN team_id
  SET DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE query_history
ALTER COLUMN season_year
  TYPE INTEGER[] USING CASE WHEN season_year IS NULL THEN ARRAY[]::INTEGER[] ELSE ARRAY[season_year] END,
ALTER COLUMN season_year
  SET DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE query_history
DROP COLUMN IF EXISTS home_team_id,
DROP COLUMN IF EXISTS away_team_id,
DROP COLUMN IF EXISTS event_type,
DROP COLUMN IF EXISTS shot_made,
DROP COLUMN IF EXISTS action_type,
DROP COLUMN IF EXISTS shot_type,
DROP COLUMN IF EXISTS basic_zone,
DROP COLUMN IF EXISTS zone_name,
DROP COLUMN IF EXISTS zone_abb,
DROP COLUMN IF EXISTS zone_range,
DROP COLUMN IF EXISTS loc_x,
DROP COLUMN IF EXISTS loc_y,
DROP COLUMN IF EXISTS shot_distance,
DROP COLUMN IF EXISTS qtr,
DROP COLUMN IF EXISTS total_time_left_secs,
DROP COLUMN IF EXISTS mins_left,
DROP COLUMN IF EXISTS secs_left,
DROP COLUMN IF EXISTS position,
DROP COLUMN IF EXISTS position_group,
DROP COLUMN IF EXISTS game_date;

ALTER TABLE query_history
ADD COLUMN IF NOT EXISTS quarter INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN IF NOT EXISTS start_game_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS end_game_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS game_location VARCHAR(20),
ADD COLUMN IF NOT EXISTS start_time_left INTEGER;

ALTER TABLE query_history
ALTER COLUMN returned_shots DROP NOT NULL,
ALTER COLUMN returned_shots SET DEFAULT 0;